### PR TITLE
2023.9

### PR DESCRIPTION
**Pull request by chrmod**
This is a huge change to Ghostery Private Browser for Android as it ship a new generation of Ghostery Tracker & Ad Blocker - v10.
It also updates browser with Firefox 117 codebase.

TODO Issues:
- [x] [Bottom menu is cut in the half](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1717429516)
- [ ] [Google Play Store v8 screenshots](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1717626335)
- [x] ["Software Licenses" opens a tab with a Ghostery settings screenshot](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1717656356)
- [ ] [Trackers Count is not showing number of blocked trackers](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1717675825)
- [ ] [Missing or outdated token](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1719093844)
- [x] [Tracker Prevention hides Tracker wheel ](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1719798437)
- [x] ["Become a Contributor" opens two new tabs.](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1719854223)
- [x] [WhoTracks.me Wheel is always visible](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1719881198)

### CODE REVIEW

**Comment by GRadziejewski** [comment]
# Iteration nr 1.

## Smoke tests on desktop
- 

## Smoke tests on mobile
- [ ] Browser: Ghostery Private Browser 2023.9 (6d239e7)
	OS: 
	GBE 

  ### Checked features
  * [ ] Install fresh (no profiles and etc)
  * [ ] Update 
  * [ ] Ghostery cannot work before onboarding
  * [ ] Onboarding
~~Enable/Disable Ghostery~~
  * [ ] Enable/Disable Ad-blocking
  * [ ] Enable/Disable Anti-tracking
  * [ ] Pause Ghostery
  * [ ] Never Consent
~~Trackers Preview~~
  * [ ] Select/Unselect any/all tracker/s
  * [ ] Sign in/out
      * [ ] Sign in and then update
      ~~Check Sync from / into another device~~
		~~Check Ghostery Settings logs~~
		~~Check Ghostery Background logs~~
  * [ ] Check account settings
  * [ ] Log into Google account and open google.com
      * [ ] Try to search anything
      * [ ] Try to search something with video
  * [ ] Log into FB
  ~~Update of the GBE~~
  * [ ] Other (from PR)

## Checked PRs / bugfixes
- 

## New issues
-

**Comment by GRadziejewski** [comment]
Issue nr 1.

**Description**
On the settings website, bottom menu is cut in the half.

**Steps to Reproduce**
1. Open Ghostery panel
2. Click on the hamburger
3. Click on Ghostery settings
4. Look at the bottom of the screen

image


**Expected results**
Bottom menu should be fully visible.


Versions

	Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 2.

**Description**
Screenshots from the Google Play Store are outdated - there are shown Ghostery v8.

**Steps to Reproduce**
1. Open Google Play Store and look for Ghostery Private Browser
2. Look at the first screen

image


**Expected results**
Screenshots in the Google Play Store must be up to date - version 10 should be visible.


Versions

	Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 3.

**Description**
After clicking on the "Software Licenses", on the first look nothing happens but User cannot click anything on the Ghostery settings. When all tabs are opened, there is a new tab with Licenses opened which contains previous "screenshot" of the tab - licenses are missing.

**Steps to Reproduce**
1. Open Ghostery panel
2. Click on the hamburger
3. Click on Ghostery settings
4. Scroll down and click on the "Software Licenses"


https://github.com/ghostery/user-agent-android/assets/40433708/9232dbaa-6330-4dc6-a0ec-23259f62064a


**Expected results**
Tab with licenses should contains Licenses.


Versions

	Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 4.

**Description**
Even if Trackers Count is turned ON, number of trackers are not visible on the browser toolbar.

**Steps to Reproduce**
1. Open Ghostery panel
2. Click on the hamburger
3. Click on Ghostery settings
4. Open WhoTracks.Me tab
5. Check status of "Trackers Count". Turn it ON

image

6. Open any website, for example https://cnn.com and wait few second
7. Look at browser toolbar - there is Ghosty icon

image

8. Open Ghostery panel, there are few trackers blocked

image

**Expected results**
When Trackers Count is turned ON, number of trackers should be visible on the browser toolbar.


Versions

	Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 5.

**Description**
Error **_"401 - token is not valid"_** appears during the attempt to sync account settings. After logging into the same account, on the first smartphone everything is working as expected. But on the second smartphone error appears during any attempts of changing the settings. There is a chance that on the second smartphone token is missing but app is still thinking and showing that I'm logged into my account.

**Steps to Reproduce**
1. Log into the account on the **first** smartphone 
2. Open any website, for example https://cnn.com and open Ghostery panel
3. Click on the hamburger and open Ghostery Settings
4. Turn OFF for example Ad-Blocking
5. Log into the account on the **second** smartphone 
6. Open any website, for example https://cnn.com and open Ghostery panel
7. Click on the hamburger and open Ghostery Settings
8. Check the settings - Ad-Blocking should be turned off
9. Still on the **second** smartphone check few other websites
10. Turn OFF also Anti-Tracking and Never-Consent
11. Switch to the **first** smartphone and open Ghostery Settings
12. Check the status of Anti-Tracking and Never-Consent - both are turned ON


https://github.com/ghostery/user-agent-android/assets/40433708/8ee5d149-da33-44fb-a795-88d1d5384a02



**Expected results**
It should be working correctly as expected. If token is missing user should be logged automatically or token should be refreshed or user should be logged out. 


Versions

	Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

**Comment by smalluban** [comment]
@chrmod @GRadziejewski Issue nr 1 is unsolvable on the extension side. I mentioned that case already in https://github.com/ghostery/ghostery-extension/pull/1173:

> Settings page is broken on Firefox if opened in a new tab (there is no way to fix it using data from the browser) - it's a bug, reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1813882. They should add env(safe-area-inset-bottom), but it returns 0

In simple words, Firefox hardly sets viewport height to be as you would start "scroll", so without top navigation and bottom navigation - they both hide if the content of the site is higher - but if you use `height: 100%` it is just broken...

**Comment by GRadziejewski** [comment]
@smalluban @chrmod So maybe for [issue nr 1](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1717429516) we can change the UI a little bit? Maybe we can place the menu on the top?

**Comment by GRadziejewski** [comment]
Tests for iteration nr 1 are finished.

**Comment by GRadziejewski** [comment]
# Iteration nr 2.

## Smoke tests on desktop
- 

## Smoke tests on mobile
- [ ] 	Browser: Ghostery Private Browser 2023.9 (#2015973547 )
	OS: Android 13 
	GBE 10.1.4

  ### Checked features
  * [ ] Updated version of Ghostery Browser Extension

- [ ] 		Browser: Ghostery Private Browser 2023.9 (6d239e7 )
	OS: Android 11 
	GBE 10.1.4

  ### Checked features
  * [ ] Updated version of Ghostery Browser Extension

## Checked PRs / bugfixes
- 

## New issues
-

**Comment by smalluban** [comment]
It's a responsive design, with different views for larger screens (including android tablets, etc). I don't have any idea how to move it to the top - as still we have to scroll not on the top level, so anything on the bottom will be cutted (if the content reaches 100% height).

**Comment by GRadziejewski** [comment]
Issue nr 6.

**Description**
Tracker Prevention hides Tracker wheel on google.com

**Steps to Reproduce**
1. Log into the account on the **first** smartphone 
2. Open any website, for example https://google.com and open Ghostery panel
3. Tracker wheel is visible
4. Click on the hamburger and open Ghostery Settings
5. Turn OFF Tracker Prevention
6. Go back to the tab with google.com and refresh it
7. Tracker wheel is not visible


https://github.com/ghostery/user-agent-android/assets/40433708/199157bf-d7ed-48c4-ad6c-e7bf29254400



**Expected results**
Tracker Prevention should not hide Tracker wheel


Versions

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 7.

**Description**
Clicking "Become a Contributor" opens two new tabs.

**Steps to Reproduce**
1. Open any website, for example https://cnn.com and open Ghostery panel
2. Scroll down and click on "Become a Contributor"
3. Click on the "all tabs" icon to show all tabs
4. There are two new tabs


https://github.com/ghostery/user-agent-android/assets/40433708/48d5175a-eb9a-4815-8df7-6a92e580e309



**Expected results**
Clicking "Become a Contributor" should open one new tabs.


Versions

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 13 
	GBE 10.1.4

**Comment by GRadziejewski** [comment]
Issue nr 8.

**Description**
Switch ON and/ or OFF WhoTracks.me Wheel on Ghostery Settings, do not hide Tracker wheel on google.com

**Steps to Reproduce**
1. Open any website, for example https://google.com
2. Tracker wheel is visible
3. Click on the hamburger and open Ghostery Settings
4. Turn OFF WhoTracks.me Wheel 
5. Go back to the tab with google.com and refresh it
6. Tracker wheel is still visible



https://github.com/ghostery/user-agent-android/assets/40433708/133b5d90-466d-4db4-a0da-cbd6441e3789



**Expected results**
WhoTracks.me Wheel should be turned on and off in Ghostery settings by clicking on the WhoTracks.me Wheel checkbox.


Versions

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 11 
	GBE 10.1.4

	Browser: Ghostery Private Browser 2023.9 (#2015973963)
	OS: Android 13 
	GBE 10.1.4

**Comment by kalinme** [comment]
I'm adding updated Google Play images, @smalluban can you update them?

[GooglePlay.zip](https://github.com/ghostery/user-agent-android/files/12620269/GooglePlay.zip)

**Comment by smalluban** [comment]
@chrmod Can you update assets? I don't have access to Google Play Console.

**Comment by GRadziejewski** [comment]
Created an issue for:
[Missing or outdated token](https://github.com/ghostery/user-agent-android/pull/41#issuecomment-1719093844) 

Here: 
https://github.com/ghostery/ghostery-extension/issues/1303

**Comment by GRadziejewski** [comment]
**Tests are finished at 15:45:00 UTC 28.09.2023.**

Test results of iteration nr 3 are here: [[QA] Tests of Release 2023.9](https://github.com/ghostery/user-agent-android/issues/43#issuecomment-1738890626)

**Pull request merged**
